### PR TITLE
Fixes "Add again" button behaviour

### PR DESCRIPTION
**Pull request by godDLL**
#5 added some broken behaviour

### CODE REVIEW

**Comment by svanlaere** [comment]
Not sure wat this does, how to use it?

Op 24-7-2016 om 20:37 schreef Yuli C.:

> Hide the prompt so select an option after selecting

**Comment by godDLL** [comment]
After you have selected a snippet, the `<option>` to "please select snippet" dissapears, as it's no longer needed.

**Comment by svanlaere** [comment]
Right that is indeed the case, so that works.

Op 24-7-2016 om 20:53 schreef Yuli C.:

> After you have selected a snippet, the `<option>` to "please select 
> snippet" dissapears, as it's no longer needed.
> 
> On Sun, Jul 24, 2016 at 9:51 pm, svanlaere < notifications@github.com

**Comment by svanlaere** [comment]
Don't you have a desire for a Hebrew i18n?

Op 24-7-2016 om 20:53 schreef Yuli C.:

> After you have selected a snippet, the `<option>` to "please select 
> snippet" dissapears, as it's no longer needed.
> 
> On Sun, Jul 24, 2016 at 9:51 pm, svanlaere < notifications@github.com

**Comment by godDLL** [comment]
Not so much, but I could do that, it's not too much work.
I'll try hunt down that bug first tho.

**Comment by svanlaere** [comment]
Don't know why, but .change() solved it for latest Firefox.

**Comment by svanlaere** [comment]
Is there a way to make it print the choosen snippet on the cursor position? (if set).

**Comment by godDLL** [comment]
Yeah, I'll look into that.
It's just that it's an external dependency, unless there's something in jQuery, I don't recall.
I'll have a look.

**Pull request merged**
