### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by godDLL**
- [ ] @svanlaere you need to update `plugin_version.xml` to point at `0.2.1`  
  Maybe you have some users that will want to update.
- [x] @svanlaere there is no mention of a license in the README
- [x] 7354993f in Download section is not auto-linked (this is from #14)

### CODE REVIEW

**Comment by svanlaere** [comment]
I've updated plugin_version.xml
Add a GPLv3 licence?

**Comment by godDLL** [comment]
That is entirely up to you.

I use MIT for stuff to give away, GPLv2 for stuff I want other people to work with me on. If there is no way for that to happen, maybe CC-BY

On Sat, Jul 30, 2016 at 11:12 am, svanlaere < notifications@github.com [notifications@github.com] > wrote:
I've updated plugin_version.xml
Add a GPLv3 licence?

**Comment by svanlaere** [comment]
So it will be a MIT license, its all free.

**Comment by godDLL** [comment]
For commercial use too.
And the GPL comes with obligation to share modifications.
MIT sounds good.

**Pull request merged**
