### PR TITLE
Add a setting to show <button>s instead of a <select>

### PR DESCRIPTION
**Pull request by godDLL**
Which means there's now a controller, a settings view, and an additional UI view.
screenshot - 240716 - 05 37 33
screenshot - 240716 - 05 51 11

I can't do NL for this, would you please? #4

### CODE REVIEW

**Comment by godDLL** [comment]
**There's a version bump in there**

**Comment by godDLL** [comment]
screenshot - 240716 - 05 37 33

**Comment by godDLL** [comment]
@svanlaere look at  d45a025 for the proposed version bump,
if the API indeed changed in 0.8.0 then I could make a PR for this.

**Comment by svanlaere** [comment]
Yes go ahead and do a pull request.

Op 24-7-2016 om 17:52 schreef Yuli C.:

**Pull request merged**
