### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by godDLL**
Continued in #14

### CODE REVIEW

**Comment by godDLL** [comment]
For review, I say, in one go, I say, nooooooo, he goes and merges it before I even get to item 3 on the list baaah

**Comment by svanlaere** [comment]
Clicked before I read it, sorry.

**Comment by godDLL** [comment]
I think I can continue pushing, and you can continue merging, let's check it out.

**Comment by svanlaere** [comment]
I guess it easier to revert back for just one change
then a couple of changes in one go?

Or doesn't that matter?

Op 27-7-2016 om 23:22 schreef Yuli C.:

**Comment by godDLL** [comment]
Can you please `git tag 0.1.0 7354993f` for me, I want to link to it, so people with 0.7.x can download that.

**Comment by godDLL** [comment]
And `http://svanlaere.nl/plugin-versions.xml` needs to be updated to include at least `0.1.0` and `0.2.1` as published versions.

**Comment by godDLL** [comment]
And no need to revert, I just make (already made) a new PR, and since it has the same commits -- it sits nicely on top of your :master

It has a TODO list, so you can see when it's ready. 
A couple of those will need your involvement @svanlaere

**Pull request merged**
